In [2]:
import numpy as np

In [3]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([['apple', 'mango', 'banana'], 
          ['guava', 'tomato', 'strawberry']])

array([['apple', 'mango', 'banana'],
       ['guava', 'tomato', 'strawberry']], dtype='<U10')

In [10]:
np.array([['pineapple', 'orange', 'kiwi'] ,
         ['straberry', 'blueberry', 'guava']])

array([['pineapple', 'orange', 'kiwi'],
       ['straberry', 'blueberry', 'guava']], dtype='<U9')

In [11]:
np.array([[True, False], [True, True], [False, True]])

array([[ True, False],
       [ True,  True],
       [False,  True]])

In [12]:
a1 = np.array([[2, 3, 5], 
               [1, 4, 6], 
               [2, 5, 7]]) 

In [13]:
len(a1)

3

In [14]:
a1[0]

array([2, 3, 5])

In [15]:
a1[-1]

array([2, 5, 7])

In [16]:
a1[2]

array([2, 5, 7])

In [17]:
a1[-3]

array([2, 3, 5])

In [19]:
a1[2]

array([2, 5, 7])